---
sidebar: sidebar
permalink: doc-gen-ai-assistant.html
keywords: netapp, generative ai, doc
summary: "Doc is our generative AI-powered assistant on docs.netapp.com. Doc is designed to respond to questions about NetApp products, using content published on docs.netapp.com."
---
= NetApp generative AI-powered assistant overview
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Doc is our generative AI-powered assistant on docs.netapp.com. Doc is designed to respond to questions about NetApp products, using content published on docs.netapp.com.

Doc can build responses from previous questions, suggest additional questions, and explain how it generates responses. This makes it a valuable tool for navigating NetApp documentation.

== Scope and limitations
Doc can answer only questions based on select content published on docs.netapp.com.

NOTE: During the Beta phase, Doc uses most but not all content published on docs.netapp.com to answer questions. Doc is familiar with all ONTAP, NetApp Console, StorageGRID, E-Series, Keystone, and SnapCenter docs and uses them to answer questions about those products. On the other hand, Doc is not familiar with some legacy products' docs. For example, Doc does not use SnapDrive for UNIX docs to provide answers. Throughout the Beta, we are working to refine Doc's knowledge. If you need information Doc doesn't have, mailto:ng-doccomments@netapp.com[let us know].

* Doc answers questions based on the latest published version of a product only. For example, if there is documentation for the 1.0 version and the 2.0 version of a product, Doc only refers to the most recent 2.0 documentation.
* For best results, always be specific with product names. Doc knows what page you are on when you ask a question, but it is only one of several factors Doc takes into consideration when formulating an answer. 
* Doc can chat in languages supported on docs.netapp.com, but isn't trained on non-English versions. 

== Writing good prompts
Follow these tips for the best experience with Doc.

Ask specific questions.:: Write detailed questions and specify the product name, version, and interface type (GUI, API). For example:
+
====
What steps should I follow in System Manager to upgrade from ONTAP 9.8 to ONTAP 9.12.1?
====

Ask for steps to complete a task.:: Ask Doc to include the steps to complete a process. Instead of asking _How do I install the NetApp Console agent without internet?_ try:
+
====
What steps should I follow to install the NetApp Console agent without internet?
====

Break complex questions into chunks.:: Break complex questions into smaller questions (also known as _chaining_). Doc remembers previous questions and builds more complex answers as you continue to chat. 
+
For example, instead of asking Doc _How do I configure ransomware protection and backup schedules in the NetApp Console?_ try:
+
====
What are the steps to configure ransomware protection in the NetApp Console?
====
+
then ask:
+
====
What are the steps to configure backup schedules in the NetApp Console?
====

Use quotation marks.:: Enclose multi-word phrases in quotation marks. This helps Doc recognize the phrase as a single concept, similar to how you might emphasize it in a conversation with a human.
+
For example, in this question, _How is storage efficiency calculated in ONTAP?_ Doc might think you're asking about _storage_ and _efficiency_ as two unrelated words. Instead try:
+
====
How is "storage efficiency" calculated in ONTAP?
====

Review how Doc responded.:: After responding, Doc provides insights into how it generated its response. This can give you ideas for how to refine your question to get the results you want. 

Clear your chat history:: If you want to change topics (for example, if you want to ask about a different product), clear the chat history to start a new session. If you don't clear the chat before starting a new topic, you might get inaccurate results. 

== Feedback
We are working to continually improve Doc. Please send us feedback inside Doc's chat window. Let us know if Doc's answers are accurate and helpful or if they're incomplete or in any way insufficient. You can also mailto:ng-doccomments@netapp.com[contact us] if you have any questions or concerns regarding Doc's capabilities or responses.