jekyll: staging
settings:
  name: "About docs.netapp.com"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
 
sidebar: 
  entries:
  - title: About the sites
    url: /docs-netapp-com.html
  - title: About Doc (AI-powered assistant)
    entries:
      - title: About NetApp generative AI assistant  
        url: /about-doc-gen-ai-assistant.html
      - title: NetApp generative AI assistant terms of use
        url: /doc-gen-ai-assistant-terms-of-use.html   
  - title: Legal notices
    url: /legal-notices.html
