settings:
  name: "About docs.netapp.com"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true

sidebar: 
  entries:
  - title: About the sites
    url: /docs-netapp-com.html
  - title: Legal notices
    url: /legal-notices.html
